default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "4"

platform :ios do

  	lane :tests do
  	run_tests(
     	  devices: ["iPhone 8"],
      	  scheme: "CalculatorReplicaSwiftUI"
    	)
	end

end