name: Testing

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane tests
  snapshot_test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run snapshot tests
      run: bundle exec fastlane snapshot_tests
  automation_test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Run automation tests
      run: bundle exec fastlane automation_tests
